# -*- coding: utf-8 -*-
"""yasemin-sireci-odev-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSftYpCbNScULiYJhChYzbQwxCeZmoZn
"""

# 1.	Kütüphane ve Veri Yükleme:
# ○	Pandas ve Numpy kütüphanelerini import edin.
# ○	Size verilen weather_data.csv dosyasını df değişkenine okuyun.

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("weather_data.csv")
df

# 2.	Veriyi Keşfetme:
# ○	Veri setinin ilk 5 satırını (head) ve son 5 satırını (tail) ekrana yazdırın.
# ○	Veri setinin istatistiksel özetini (describe) görüntüleyin.

df.head()
#df.head(5)

df.tail()
#df.tail(5)

df.describe()

# 3.	Sütun Seçimi:
# ○	Sadece Date, City ve Temperature sütunlarını seçerek yeni bir görünüm oluşturun ve ekrana yazdırın.
# ○	City ve Temperature kolonlarını birlikte listeleyiniz.

df[['Date','City','Temperature']]

df[['City', 'Temperature']]

# 4.	Basit Filtreleme:
# ○	Hava sıcaklığı (Temperature) 30 derecenin üzerinde olan kayıtları listeleyin.
# ○	Şehri (City) sadece "Bursa" olan kayıtları listeleyin.

df[df['Temperature'] > 30]

df[df['City'] == 'Bursa']

# 5.	Mantıksal Operatörler ile Filtreleme:
# ○	Şehri "İstanbul" olan VE Nem oranı (Humidity) 60'tan büyük olan kayıtları listeleyin.
# ○	Şehri "Ankara" olan VEYA Sıcaklığı 5 dereceden küçük olan kayıtları listeleyin.
# ○	Sıcaklığı 10°C altında veya nemi (Humidity) %70 üzerinde olan verileri filtreleyiniz.

df[(df['City'] == 'İstanbul') & (df['Humidity'] > 60)]

df[(df['City'] == 'Ankara') | (df['Temperature'] < 5)]

df[(df['Temperature'] < 10) | (df['Humidity'] > 70)]

# 6.	Sıralama (Sorting):
# ○	Veri setini Temperature (Sıcaklık) değerine göre büyükten küçüğe (azalan) sıralayın ve ilk 10 kaydı gösterin.
# ○	Veriyi neme göre azalan şekilde sıralayınız.
# ○	Veriyi Şehir alanına göre Artan şekilde sıralayanız.

df.sort_values('Temperature', ascending=False).head(10)

df.sort_values('Humidity', ascending=False)

df.sort_values('City', ascending=True)

# 7.	Yeni Sütun Ekleme:
# ○	Veri setine Temperature_F adında yeni bir sütun ekleyin. Bu sütun, sıcaklığın Fahrenheit cinsinden değerini taşımalıdır.
# ○	Formül: (Temperature * 9/5) + 32
# ○	"FeelsLike" isminde yeni bir kolon oluşturun. Formül:
# ○	FeelsLike = Temperature - (Humidity / 100)

df['Temperature_F'] = (df['Temperature'] * 9/5) + 32
df

df['FeelsLike'] = df['Temperature'] - (df['Humidity'] / 100)
df

# 8.	Gruplama (Grouping) ve Analiz:
# ○	Her şehirde (City) kaç adet veri kaydı olduğunu hesaplayın.
# ○	Şehirlere göre ortalama sıcaklık (Temperature) değerlerini hesaplayın.

df.groupby('City')['Date'].count()

sehir_sicakliklari = df.groupby('City')['Temperature'].mean()
sehir_sicakliklari

# 9.	En Yüksek/Düşük Değer Analizi:
# ○	En yüksek sıcaklığın olduğu satırı (tüm bilgilerini) bulun ve yazdırın.
# ○	En düşük nem oranının olduğu satırı bulun ve yazdırın.

df['Temperature'].idxmax()

df.loc[df['Temperature'].idxmax()]

df['Humidity'].idxmin()

df.loc[df['Humidity'].idxmin()]

# 10.	Dışa Aktarma (Export):
# 8.	maddede bulduğunuz "Şehirlere göre ortalama sıcaklık" tablosunu bir Excel (sehir_sicakliklari.xlsx) veya CSV dosyası olarak kaydedin.

# sehir_sicakliklari.to_excel('sehir_sicakliklari.xlsx')

sehir_sicakliklari.to_csv('sehir_sicakliklari.csv')

import os

print(os.path.exists('sehir_sicakliklari.csv'))